### ISSUE TITLE
  File "</usr/local/lib/python3.10/dist-packages/nvidia_tao_deploy/cv/common/entrypoint/entrypoint_hydra.py>", line 1, in <module>   File "<frozen cv.common.entrypoint.entrypoint_hydra>", line 30, in <module>   File "/usr/local/lib/python3.10/dist-packages/pycuda/driver.py", line 66, in <module>     from pycuda._driver import *  # noqa ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by monajalal** [NVIDIA/tao_deploy#10]
I am getting this error

```
(main)$ docker run -it -v /hdd/tao-experiments/centerpose/results/export:/workspace/models -v /home/mona/tao_tutorials/:/tao_tutorials -v /hdd/tao-experiments:/tao-experiments -v /hdd/tao-experiments/data/centerpose:/data nvcr.io/nvidia/tao/tao-toolkit:5.3.0-deploy

=======================
=== TAO Toolkit Deploy ===
=======================

NVIDIA Release 5.3.0-Deploy (build 76057045)
TAO Toolkit Version 5.3.0

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the TAO Toolkit End User License Agreement.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/tao-toolkit-software-license-agreement

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .

root@9d46cd51618b:/opt/nvidia# centerpose gen_trt_engine -e /tao_tutorials/notebooks/tao_launcher_starter_kit/centerpose/specs/gen_trt_engine.yaml gen_trt_engine.onnx_file=/workspace/models/centerpose_model.onnx gen_trt_engine.trt_engine=/workspace/centerpose_model.engine results_dir=/workspace/models/
Traceback (most recent call last):
  File "/usr/local/bin/centerpose", line 5, in <module>
    from nvidia_tao_deploy.cv.centerpose.entrypoint.centerpose import main
  File "</usr/local/lib/python3.10/dist-packages/nvidia_tao_deploy/cv/centerpose/entrypoint/centerpose.py>", line 3, in <module>
  File "<frozen cv.centerpose.entrypoint.centerpose>", line 40, in <module>
  File "</usr/local/lib/python3.10/dist-packages/nvidia_tao_deploy/cv/common/entrypoint/entrypoint_hydra.py>", line 1, in <module>
  File "<frozen cv.common.entrypoint.entrypoint_hydra>", line 30, in <module>
  File "/usr/local/lib/python3.10/dist-packages/pycuda/driver.py", line 66, in <module>
    from pycuda._driver import *  # noqa
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

```

and

```
(base) mona@DOS:~$ nvidia-smi
Wed May 29 15:12:08 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.67                 Driver Version: 550.67         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3080 ...    Off |   00000000:01:00.0 Off |                  N/A |
| N/A   41C    P0            752W /   90W |       9MiB /  16384MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      5952      G   /usr/lib/xorg/Xorg                              4MiB |
+-----------------------------------------------------------------------------------------+
(base) mona@DOS:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0
(base) mona@DOS:~$ uname -a
Linux DOS 6.5.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue May  7 09:00:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
(base) mona@DOS:~$ lsb_release -a
LSB Version:	core-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
(base) mona@DOS:~$ tao info 
Configuration of the TAO Toolkit Instance
task_group: ['model', 'dataset', 'deploy']
format_version: 3.0
toolkit_version: 5.3.0
published_date: 03/14/2024
```

can you please guide how to get it fixed?

```
(base) mona@DOS:~$ locate libcuda.so.1
/usr/lib/i386-linux-gnu/libcuda.so.1
/usr/lib/x86_64-linux-gnu/libcuda.so.1
/var/lib/flatpak/runtime/org.freedesktop.Platform.GL.nvidia-530-30-02/x86_64/1.4/1b100a6f4a85db99c82050bcbfacad73a2ae66e6e4b9aabdc0a7610f104243df/files/extra/libcuda.so.1

```

```
(base) mona@DOS:~$ echo $LD_LIBRARY_PATH
/usr/lib/cuda/lib64:/usr/local/lib:/home/mona/MVTec/HALCON-23.05-Progress//lib/x64-linux:/usr/local/cuda-11.7/lib64:/home/mona/onnx-tensorrt/build::/home/mona/percv_workspace/TensorRT-860/lib

```

**Comment by monajalal** [comment]
The following resolved the issue for me (I had nvidia-docker 2 but since I had updated the cuda and nvidia driver, I didn't upgrade the nvidia-docker2)

```
distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
   && curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - \
   && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
   
sudo apt-get update

sudo apt-get install -y nvidia-docker2

sudo systemctl restart docker
```

https://github.com/NVIDIA/nvidia-docker/issues/1034#issuecomment-999637742
